Python3 port
zopefoundation/Products.PythonScripts pull request #4
Opened 2017-06-08 11:30 UTC by icemac

I created a PR of this branch to increase its visibility.

@stephan-hof Is this branch ready to merge?

2017-06-08 16:21 UTC, tseaver requested changes

2017-06-08 16:21 UTC, tseaver commented on buildout.cfg
> +RestrictedPython =
Shouldn't we be relying on the now-released versions published via https://raw.githubusercontent.com/zopefoundation/Zope/master/versions.cfg (or even better, https://zopefoundation.github.io/Zope/releases/master)?

2017-06-08 16:21 UTC, tseaver commented on tox.ini
> +    # flake8,
Why are we checking in commented-out environments?

2017-06-08 16:21 UTC, tseaver commented on tox.ini
> +install_command = pip install --no-cache-dir --no-binary=:all: {opts} {packages}
Needs a comment explaining why we are overriding `install_command`.

2017-06-08 16:21 UTC, tseaver commented on tox.ini
> +    PIP_NO_CACHE = 1
Needs a comment explaining why.

2017-06-08 16:21 UTC, tseaver commented on tox.ini
> +commands = flake8 --doctests src tests setup.py
These three testenv's should be either removed here or uncommented above.

2017-06-08 16:23 UTC, tseaver commented
I would find it easier to review if the PR were rebased, with at least some commits squashed, to make  reviewing by commit easier.

2017-06-08 18:15 UTC, stephan-hof commented
I'm sorry for all this small commits, I just committed on every test I fixed. I thought it is easier to review. I have no problem in squashing/rebasing them into a single commit.
Unfortunately rebasing is a disruptive operation, history is changed. So when it's done, other people having local (not pushed) commits get into trouble when pulling again.
So I'm reluctant to do it right away. It looks that other people like icemac are working on that branch as well and I don't want to destroy their local branches.
 
Another thing where I just need confirmation. The target python versions are
* python2 = 2.7
* python 3 >= 3.4
right ?

I'm not sure what should happen with the tox.ini file. Right now travis is using just buildout and there are no issues. I would vote for removing the file from this branch to work on it in a separate pull request. IMHO this flake8/coverage is an independent thing and not strongly required for the python3 port.

2017-06-09 07:32 UTC, icemac commented
@tseaver I think I have addressed all your comments regarding tox.ini and buildout.cfg.

2017-06-09 16:18 UTC, tseaver approved these changes

2017-06-16 06:18 UTC, merged